# Generated by Django 3.2.3 on 2021-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masukkan nama mentor', max_length=100)),
                ('email', models.EmailField(help_text='Masukkan email mentor', max_length=125)),
                ('price', models.IntegerField(help_text='Masukkan biaya per menit')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
